### ISSUE TITLE
Canvas Displays are just black in Virtual Cockpit with compositor

### ISSUE THREAD

**Issue by merspieler** [JMaverick16/Airbus_A330#11]
In the Virtual Cockpit, all canvas displays(PFD, ND, Upper and Lower ECAM) are just black.
The popups show them just fine.

This happens under compositor.
It isn't fg as the A320 works.

**Comment by Octal450** [comment]
That sounds like the display shader. Comment it out of the XML and see if that fixes it.

Kind Regards,
Josh

**Comment by merspieler** [comment]
No longer happens with latest fg
