### ISSUE TITLE
Cockpit displays are White

### ISSUE THREAD

**Issue by mohamedaissa** [JMaverick16/Airbus_A330#14]
The cockpit dispalys are white when using model shader 
FG version: 2020.2.1
latest version of the A330
![fgfs-20201014162249](https://user-images.githubusercontent.com/72527643/96017711-9bd92480-0e4a-11eb-91b2-7849b6dd7726.png)

**Comment by mohamedaissa** [comment]
Why do this happen

**Comment by JMaverick16** [comment]
What's your PC specs?

**Comment by mohamedaissa** [comment]
Intel(R) Core(TM) i7 CPU
RAM 16Go
system type: 64bits

If i'm right

**Comment by JMaverick16** [comment]
GPU?

**Comment by mohamedaissa** [comment]
ATI fire pro V4800 : 4Go

**Comment by mohamedaissa** [comment]
the displays are normal when the model shader are to 0

**Comment by JMaverick16** [comment]
Seeing the GPU is an ATI I think it's due to that. Right now there isn't a solution in FG that I know of.

**Comment by mohamedaissa** [comment]
ok thanks

**Comment by mohamedaissa** [comment]
i'm just gonna put the model to 0 when flying this amazing plane

good job

continue the great job guys

**Comment by merspieler** [comment]
@mohamedaissa does this happen on the A320 as well?
If not, than this is an A330 issue and you can reopen it.
