### ISSUE TITLE
IRS HDG and ATT doesn't align on manual start

### ISSUE THREAD

**Issue by puku-777** [JMaverick16/Airbus_A330#19]
All three IRU to NAV does not make artificial horizon or compass come alive from red `ATT` and `HDG` banners.
All three to ATT and combinations in between do not achieve desired result either.
`Aircraft config` dialog → `Ready for Takeoff` panel state *does however* bring operational PFD with it.
First time actually writing an issue here or anywhere; open to suggestions for how to fly the thing... I may well have missed something. Bug not reproduced on other MRTT or any other A330s.

**Comment by FirstOfficerDelta** [comment]
Check the A33X-Notes.pdf, everything you need to fly the A330 is already there. You should select the “Align IRS” in the A330 MCDU (flight computer) in order to finish the alignment.

**Comment by puku-777** [comment]
Good catch, thanks! Also, should I consider any difference between setting any of the three to ATT instead of NAV? (not well-versed in what each IRU does IRL)

**Comment by merspieler** [comment]
You should set all three to the NAV position.  
Alignment takes a few minutes.

Tho I've had this issue as well...

**Comment by legoboyvdlp** [comment]
The A320 uses GPS, the A330 uses the older method where you have to press ALIGN IRS on a reference position
