### ISSUE TITLE
Error on Flightgear start up

### ISSUE THREAD

**Issue by Tmfmo** [JMaverick16/Airbus_A330#31]
When I'm starting up Flightgear it gives me an error about error of IAS property.
I've reinstalled it about 3 rows
_Error on screenshot below:_
![image](https://user-images.githubusercontent.com/83754334/127624293-8767942d-5b38-47c6-899d-94556871f828.png)

**Comment by legoboyvdlp** [comment]
its such a shame that there is a file INSTALL.MD with installation instructions which nobody bothers to read 😢

**Comment by Tmfmo** [comment]
I'm sorry
