### ISSUE TITLE
fgfs prompts throttle is unavailable

### ISSUE THREAD

**Issue by clonetrooper-corporal** [JMaverick16/Airbus_A330#32]
![Screenshot 2021-08-02 184659](https://user-images.githubusercontent.com/88355405/127940691-557d069d-da7c-459d-b667-c1a9af37a574.png)
Here is the proof.

**Comment by Octal450** [comment]
Did you remove the -master????

Kind Regards,
Josh

**Comment by clonetrooper-corporal** [comment]
No. Could you tell me how?

**Comment by clonetrooper-corporal** [comment]
Oh, you meant the name.

**Comment by clonetrooper-corporal** [comment]
It works now. Thank you!

**Comment by Octal450** [comment]
No problem enjoy.

Kind Regards,
Josh
